### ISSUE TITLE
Bug: HealthEstimateOverlay disappears/disalign when switching maps

### ISSUE THREAD

**Issue by elizeuangelo** [Shylight/healthEstimate#10]
As of 0.7.6, DnD 5e 0.98, when I switch maps the healthestimateoverlay stop working properly. Depending on the map, sometimes it greatly disaligns and others it simply disappears all together. Looking at the console it seems the healthestimateoverlay IS rendering, meaning it must be somewhere off-screen?

When returning to the original map, the issue persists, I need to refresh to fix the issue on any map.

**Comment by elizeuangelo** [comment]
Update:

Testing I figured out why this happens:

The `<div id="HealthEstimate">` is originally inside the `<div id="hud">`, when you switch maps it gets destroyed and is pushed to the `body` tag. When it is in the body tag it doesnt work properly.

**Comment by sirrus233** [comment]
OOC, what version of HealthEstimate are you using? This sounds similar to the issue I reported in https://github.com/Shylight/healthEstimate/issues/5 , which was present in 2.0.2 but seems to have been resolved in 2.0.3

**Comment by elizeuangelo** [comment]
Nevermind... just updated it and its working now! Sorry about this
