### ISSUE TITLE
Anyway we could get an Uninjured check?

### ISSUE THREAD

**Issue by valdier1** [Shylight/healthEstimate#12]
When a creature is at full health, it uses the last label in a list. If they have 50 health, it is 'uninjured' and takes 1 damage, it's still showing uninjured.

In 5e, there are effects that trigger when a creature is actually uninjured. Anyway to set an actual uninjured status?

**Comment by Cerebus0** [comment]
I concur. I have a player that is bugged so much by taking damage and it still saying UNINJURED that he raised such a stink that the rest of the players just finally told me to turn it off.
