### ISSUE TITLE
Health estimate is extremely misaligned

### ISSUE THREAD

**Issue by sirrus233** [Shylight/healthEstimate#5]
See attached image for example:

![image](https://user-images.githubusercontent.com/8885220/98463940-13f9e800-2174-11eb-918e-d8d888dae879.png)

Health Estimate Version: 2.0.2
FoundryVTT Version: 0.7.6
PF2e System Version: 1.10.15.2210

When the world is started, the labels are correct, and they stay that way until the first time the scene is changed.

**Comment by Bryn1701** [comment]
Same for me. Running Health Estimate Version 2.0.2
FoundryVTT Version 0.7.5
D&D 5E Version 0.98 
No other modules running for testing purposes. For a moment I thought the module wasn't working at all, until I saw the WAAY offset health estimate bottom right. 

https://gyazo.com/4ec7253c26f2f9cb0ae7a685173da240

**Comment by sirrus233** [comment]
This is resolved as of version 2.0.3, although I do continue to see the issue presented in https://github.com/Shylight/healthEstimate/issues/6
