### ISSUE TITLE
Having some alignment issues still

### ISSUE THREAD

**Issue by Bryn1701** [Shylight/healthEstimate#6]
Installed the new update, it's no longer misaligned, but there is a new issue. When you rotate the token, the Health Estimate also goes out of alignment. Here is a quick example. https://gyazo.com/6c23bf68c7b517aaa1aae8182d72427f

Also I was curious if it was possible to make the configuration of the colours and what gradient to be client side? So players can pick their own? I have a coloured blind player who has issues seeing the colour gradient, but don't want to turn off all colour for me and the other players.

**Comment by Aeristoka** [comment]
Having these same alignment issues on 2.0.3:
Fine:
![image](https://user-images.githubusercontent.com/7988297/98488717-02522800-21e8-11eb-8d91-9e5f938da70e.png)

Broken:
![image](https://user-images.githubusercontent.com/7988297/98488724-09793600-21e8-11eb-900b-8a86f9ad2457.png)

Broken:
![image](https://user-images.githubusercontent.com/7988297/98488737-1138da80-21e8-11eb-9c32-1c5315203d83.png)

Perhaps related to the length of the NPCs Token Name?
![image](https://user-images.githubusercontent.com/7988297/98488750-201f8d00-21e8-11eb-86df-341f5b8ca447.png)

**Comment by chozma** [comment]
Can confirm that token names over a certain length cause alignment problems when the healthEstimate values are set on hover.

**Comment by chozma** [comment]
Alignment issue seems resolved as of 2.1.0. Fast work, thanks! Very happy to see this module being updated again; it's easily one of my favourites, and it's much appreciated by many. :)

**Comment by Aeristoka** [comment]
I concur with chozma, looks nicely fixed.

Thanks SO MUCH for a very nice Quality of Life improvement module for me and my players.
