### ISSUE TITLE
Status doesn't update

### ISSUE THREAD

**Issue by laurieathey** [Shylight/healthEstimate#9]
I am a touch confused but I just installed this cause: Awesome! and then went to a full health token, mousover, Uninjured, coooool, did one damage to it, mouse over again... uninjured...?
Refreshed, still uninjured, double checked the health, 94/95hp. Should be at whatever the first stage of being injured is called.
Top right, current health, sort of middle middle, there's what their max HP is, and obviously it says uninjured.
![image](https://user-images.githubusercontent.com/11553364/98554750-6127a800-22a1-11eb-8e88-124d89d5a7a3.png)
And I tried doing more damage, same thing.
![image](https://user-images.githubusercontent.com/11553364/98554885-89afa200-22a1-11eb-9679-1cd2b001d831.png)

I tried the module a few months ago as well when I picked up foundry and it had the same issue back then.
I tested it on my "test" game where there's nothing but that module activated and have the same issue.

PF2e, literally just updated the game system so we're on: 1.10.15.2210
healthEstimate: 2.0.3
Foundry 0.7.5

**Comment by sirrus233** [comment]
I'm using the same versions of PF2e, healthEstimate, and Foundry. I believe the module is working as intended here. By default, there are 6 "stages" of health, "Unconscious, Near Death, Badly Injured, Injured, Barely Injured, Uninjured". The health estimate for the enemy is divided into a number of "bins" equal to the number of stages - 1. So by default we have:

Uninjured = 100% - 80%
Barely Injured = 80% - 60%
Injured = 60% - 40%
Badly Injured = 40% - 20%
Near Death = 20% - 0%
Dead = 0%

I believe if you adjust your 95 HP health creature's HP to 76/95 (about 80%), it will show as barely injured.

AFAIK, there is no way to get healthEstimate to start the first damage stage after the first hit point lost, although you can add more damage stages if you want to decrease the size of the stage damage ranges.

**Comment by laurieathey** [comment]
Whaaaaat...
But... They are injured... 
My next request was gonna be customizable windows cause my team only uses Uninjured -> injured (<100%) -> Bloodied (<50%) and Near Death (<20%)

I... Seriously, can I change that? 
Just checked, I sort of can... Like you said I can add more, so to save anyone else time that wants to change this:

`Dead,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Near Death,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Bloodied,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Injured,Uninjured`

That's should show the %s and I listed above, just paste it into the Stages box in the settings.

**Comment by Merudo** [comment]
Someone at 85% health definitely has injuries, and is therefore not "Uninjured" by definition.

I suggest the the status be changed to something more logical:

Uninjured = 100%
Near Uninjured: 80% - 100%
Barely Injured = 80% - 60%
Injured = 60% - 40%
Badly Injured = 40% - 20%
Near Death = 20% - 0%
Dead = 0%

**Comment by Shylight** [comment]
> Someone at 85% health definitely has injuries
That really is up for interpretation. IMO at that point you'd have a couple scratches and bruises at most, not _injuries_. 

It doesn't matter much, however, since I'm working on settings that will let you adjust this as you see fit, though the amount of changes I need to do is vast, so it'll take a bit of time to finish.

**Comment by Shylight** [comment]
Since my preferred way to solve this is taking too long, I've made a temporary solution. Hopefully it's helpful.
